//
// Created by Jiayi on 2022/3/6.
//

#include "book_management.h"


//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books()
{
        FILE *fp1=fopen("books.txt","wb");//w?wb?
        Book *node =book_head->next;
        while(node){
            fwrite(node,sizeof(Book),1,fp1);
            node=node->next;
        }
        fclose(fp);
        return 0;

//    else{
//        printf("An error occured");
//    }
}


//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books("books.txt");
{
    book_head=(Book*)malloc(sizeof(Book));
    book_head->next=NULL;
    book_num=0;
    FILE *fp2=fopen("books.txt","rb");
    if(fp2!=NULL){
        Book *node=book_head;
        Book* bk=(Book*)malloc(sizeof(Book));
        while(fread(bk,sizeof(Book),1,fp2)){
            node->next=node;
            book_num++;
            bk=(Book*)malloc(sizeof(Book));
            node=node->next;
        }
        fclose(fp2);
    }
    else{
        fp2=fopen("books.txt","wb");
        printf("Fail to load books.");
        fclose(fp2);
        exit(0);
    }
}


//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(Book book);